name: CI to Docker Hub
# 特定のタグがある場合のみHubに送信
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # $GITHUB_WORKSPACE以下のrepoを調べ、ワークフローがアクセスできるようにする
      - name: Check Out Repo
        uses: actions/checkout@v2

      #キャッシュの作成と復元をサポート
      # path: キャッシュを保存するパス
      # key: キャッシュを識別 osの種類-buildx-Githubのハッシュ値
      # restore-keys: キャッシュを復元するキーのパターンマッチ
      # マッチしていればイメージをダウンロードする必要もDockerHubから取得する回数も減る
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # DockerHubにログイン
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        # secretsから入手
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      # Build -> push(構築cacheを利用)
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./python-docker/
          file: ./python-docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale.latest
          build-args: BUILDX_BUILDER=image-builder

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          
    
